language: node_js

node_js:
   - "10"

jobs:
  include:
  - stage: build
    script:
      - npm run test

  - stage: aws Publish
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET_NAME
    skip_cleanup: true
    local_dir: public
    on:
      branch: main

  - stage: npm Deployment
    deploy:
      edge: true
      provider: npm
      skip_cleanup: true
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      on:
        tags: true
